test: True
cr_redirect: en.wikipedia.org

ingest:
  table_name: ingest
  api: /ingest
  stage: Ingest
  database_name: bpm_test
  ignore:
    - bpm_id

tracking:
  table_name: tracking
  api: /tracking
  stage: Tracking
  database_name: bpm_test
  target: validation_outputs
  ignore:
    - validation_outputs

error:
  table_name: errors
  api: /errors
  stage: Tracking
  database_name: bpm_test

allocations:
  table_name: allocations
  api: /allocate
  stage: Allocation
  database_name: bpm_test

users:
  table_name: users
  api: /users
  stage: Allocation
  database_name: bpm_test
